name: Docker

on:
  schedule:
    - cron: '0 1 * * *'
  pull_request:
    branches: [ "master" ]
    
env:
  BASE_IMAGE: nginx:alpine
  IMAGE_NAME: pruh/nginx-with-modules:alpine

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Docker Image Update Checker
        id: baseupdatecheck
        uses: lucacome/docker-image-update-checker@v1.1.1
        with:
          base-image: ${{ env.BASE_IMAGE }}
          image: ${{ env.IMAGE_NAME }}
          verbose: true
        if: false
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4.2.0
        with:
          images: ${{ env.BASE_IMAGE }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
        # if: steps.baseupdatecheck.outputs.needs-updating == 'true'

          
      - name: Debug
        run: echo {{ steps.baseupdatecheck.outputs }}
    
      - name: Set NGINX alpine version
        id: version
        run: |
          nginx_alpine=library/nginx:$(grep -m1 "FROM.*nginx:.*alpine" < build/Dockerfile | awk -F"[ :]" '{print $3}')
          echo "::set-output name=matrix::[{\"version\": \"${nginx}\", \"distro\": \"debian\"}, {\"version\": \"${nginx_alpine}\", \"distro\": \"alpine\"}, {\"version\": \"${nginx_ubi}\", \"distro\": \"ubi\"}]"


      # only execute subsequent steps if an update is actually NEEDED.
      # unfortunately we need to add an if-condition to all steps now
      # because a clean exit can't be triggered within a job it seems
      # (a cancellation is NOT the same and triggers a failure email)
      # see also https://github.com/actions/runner/issues/662

#       - name: Login to DockerHub
#         uses: docker/login-action@v2.1.0
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
#         if: steps.baseupdatecheck.outputs.needs-updating == 'true'

#       - name: Build and push Docker images
#         uses: docker/build-push-action@v3.2.0
#         with:
#           context: "${{ github.workspace }}"
#           push: true
#           tags: pruh/nginx-with-modules
#         if: steps.baseupdatecheck.outputs.needs-updating == 'true'
