name: Docker

on:
  schedule:
    - cron: '0 1 * * *'
  pull_request:
    branches: [ "master" ]
    
env:
  BASE_IMAGE: nginx
  IMAGE_TAG: alpine
  IMAGE_NAME: pruh/nginx-with-modules

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Docker Image Update Checker
        id: baseupdatecheck
        uses: giggio/docker-image-update-checker@v2.0.0
        with:
          base-image: ${{ env.BASE_IMAGE }}:${{ env.IMAGE_TAG }}
          image: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          verbose: true

      - name: Debug
        run: echo ${{ steps.baseupdatecheck.outputs }}
          
      - name: Get base image latest version
        id: version
        run: | 
              curl -L --fail "https://hub.docker.com/v2/repositories/library/${{ env.BASE_IMAGE }}/tags/?page_size=100" | 
                jq '.results | .[] | .name' -r |
                grep -Po "(\d+\.)+\d+(-${{ env.IMAGE_TAG }})" |
                sed 's/-alpine//' |
                sort --version-sort |
                tail -n 1
        if: steps.baseupdatecheck.outputs.needs-updating == 'true'

      - name: Print version
        run: echo ${{ steps.version.outputs }}
        if: steps.baseupdatecheck.outputs.needs-updating == 'true'

      # only execute subsequent steps if an update is actually NEEDED.
      # unfortunately we need to add an if-condition to all steps now
      # because a clean exit can't be triggered within a job it seems
      # (a cancellation is NOT the same and triggers a failure email)
      # see also https://github.com/actions/runner/issues/662

#       - name: Login to DockerHub
#         uses: docker/login-action@v2.1.0
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
#         if: steps.baseupdatecheck.outputs.needs-updating == 'true'

#       - name: Build and push Docker images
#         uses: docker/build-push-action@v3.2.0
#         with:
#           context: "${{ github.workspace }}"
#           push: true
#           tags:
#             - ${{ env.IMAGE_NAME }}:latest
#             - ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
#             - ${{ env.IMAGE_NAME }}:${{ steps.version.outputs.id }}-${{ env.BASE_IMAGE_TAG }}
#         if: steps.baseupdatecheck.outputs.needs-updating == 'true'
