name: Docker

on:
  schedule:
    - cron: '0 1 * * *'
  pull_request:
    branches: [ "master" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Docker Image Update Checker
        id: baseupdatecheck
        uses: lucacome/docker-image-update-checker@v1.1.1
        with:
          base-image: nginx:alpine
          image: pruh/nginx-with-modules # update for your image
          
      - name: Debug
        run: echo {{ steps.baseupdatecheck.outputs }}

      # only execute subsequent steps if an update is actually NEEDED.
      # unfortunately we need to add an if-condition to all steps now
      # because a clean exit can't be triggered within a job it seems
      # (a cancellation is NOT the same and triggers a failure email)
      # see also https://github.com/actions/runner/issues/662

#       - name: Login to DockerHub
#         uses: docker/login-action@v2.1.0
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
#         if: steps.baseupdatecheck.outputs.needs-updating == 'true'

#       - name: Build and push Docker images
#         uses: docker/build-push-action@v3.2.0
#         with:
#           context: "${{ github.workspace }}"
#           push: true
#           tags: pruh/nginx-with-modules # update for your image
#         if: steps.baseupdatecheck.outputs.needs-updating == 'true'
